items/urls.py
from django.conf.urls import url

from items import views

urlpatterns = [
    url(r'^user_items/(?P<page>[0-9]+)/$', views.user_items),
    url(r'^user_request/(?P<page>[0-9]+)/$', views.user_request),
    url(r'^page/(?P<page>[0-9]+)/$', views.list_items),
    url(r'^request_alert$', views.request_alert),
    url(r'^my_ad_alert$', views.my_ad_alert),
    url(r'^delete/$', views.delete),
    url(r'^del_img/$', views.del_item_image),
    url(r'^latest/$', views.latest),
    url(r'^cancel_demand/$', views.cancel_demand),
    url(r'^report/$', views.report),
    url(r'^edit_item/(?P<item>[0-9]+)/$', views.add_item, name='edit_item'),
    url(r'^add_item/$', views.add_item, name='add_item'),
    url(r'^details/(?P<item_id>[0-9]+)/$', views.item_details, name='item_details'),
    url(r'^reservation/$', views.reservation, name='reservation'),
    url(r'^delivery/$', views.delivery, name='delivery'),
    url(r'^add_transaction/', views.reservation, name='add_transaction'),
    url(r'^list/(?P<child_id>[0-9]+)/$', views.list_items, name='list_item_child'),
    url(r'^$', views.list_items, name='index'),
]

je_prends_je_donne/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    # Examples:
    url(r'^$', 'home.views.index', name='home'),
    url(r'^reglements', 'home.views.reglements', name='reglements'),
    url(r'^fonctionnement$', 'home.views.fonctionnement', name='fonctionnement'),
    url(r'^child_categories/', include('child_categories.urls', namespace='child')),
    url(r'^parent_categories/', include('parent_categories.urls', namespace='parent')),
    url(r'^items/', include('items.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('authenticate.urls', namespace = 'authenticate')),
    url(r'^user_profile/', include( 'user_profile.urls', namespace='user_profile')),
    url(r'^comments/', include( 'comments.urls', namespace='comments')),
    url(r'^messaging/', include( 'messaging.urls', namespace='messaging')),
#    url(r'^transactions/PayPal_IPN', include('paypal.standard.ipn.urls', namespace='PayPal_IPN')),
    url(r'^transactions/', include('transactions.urls', namespace='transactions')),
    url(r'^trasactions/', include('transactions.urls', namespace='transactions')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT,}),
]

suivant/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    # Examples:
    url(r'^$', 'home.views.index', name='home'),
    url(r'^reglements', 'home.views.reglements', name='reglements'),
    url(r'^termes', 'home.views.termes', name='termes'),
    url(r'^fonctionnement$', 'home.views.fonctionnement', name='fonctionnement'),
    url(r'^child_categories/', include('child_categories.urls', namespace='child')),
    url(r'^parent_categories/', include('parent_categories.urls', namespace='parent')),
    url(r'^items/', include('items.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('authenticate.urls', namespace = 'authenticate')),
    url(r'^user_profile/', include( 'user_profile.urls', namespace='user_profile')),
    url(r'^comments/', include( 'comments.urls', namespace='comments')),
    url(r'^messaging/', include( 'messaging.urls', namespace='messaging')),
#    url(r'^transactions/PayPal_IPN', include('paypal.standard.ipn.urls', namespace='PayPal_IPN')),
    url(r'^transactions/', include('transactions.urls', namespace='transactions')),
    url(r'^trasactions/', include('transactions.urls', namespace='transactions')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT,}),
]

comments/models.py
from django.db import models
from django.contrib.auth.models import User
from items.models import Item

class Comment(models.Model):
    
    id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User, related_name='user', db_column='user_id')
    item_id = models.ForeignKey(Item, related_name='comments', db_column='item_id')
    comment = models.TextField()
    viewed = models.BooleanField( default = False )
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
        
    class Meta:
        db_table = 'items_comments'
        
    def __unicode__(self):              # __unicode__ on Python 2
        return self.comment

items/models.py
from django.db import models
from django.contrib.auth.models import User
from child_categories.models import ChildCategorie
from stdimage import StdImageField

class Item(models.Model):
    
    id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User, related_name='user_id', db_column='user_id')
    title = models.CharField(max_length=50)
    description = models.TextField()
    credit = models.IntegerField()
    child_category_id = models.ForeignKey(ChildCategorie, related_name='child_category', db_column="child_category_id")
    status = models.ForeignKey('item_status.ItemStatus', related_name='status', db_column="status_id")
    img1 = StdImageField(upload_to = 'items/', blank = True, variations={'large': (800, 600), 'medium': (320, 240, True),'thumbnail': (200, 150)})
    img2 = StdImageField(upload_to = 'items/', blank = True, variations={'large': (800, 600), 'medium': (320, 240, True),'thumbnail': (200, 150)})
    img3 = StdImageField(upload_to = 'items/', blank = True, variations={'large': (800, 600), 'medium': (320, 240, True),'thumbnail': (200, 150)})
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
        
    class Meta:
        db_table = 'items'

    def __unicode__(self):              # __unicode__ on Python 2
        return self.title
    
class ItemReservation(models.Model):
    id = models.AutoField(primary_key=True)
    taker = models.ForeignKey(User, db_column='taker_id', null = True )
    item = models.ForeignKey(Item, db_column='item_id', related_name='reservations', null = True )
    note = models.TextField( null = True )
    viewed = models.BooleanField( default = False )
    accepted = models.BooleanField( default = None )
    created = models.DateTimeField( auto_now = False, auto_now_add = True )
    modified = models.DateTimeField(auto_now=True)
        
    class Meta:
        db_table = 'items_reservations'

    def __unicode__(self):              # __unicode__ on Python 2
        return self.item
        
class ItemDelivery(models.Model):
    id = models.AutoField(primary_key=True)
    item_reservation = models.ForeignKey(ItemReservation, db_column='item_reservation_id', related_name='delivery', null = True )
    giver_note = models.TextField( null = True )
    giver_conf = models.BooleanField( default = False )
    giver_conf_date = models.DateTimeField( null = True )
    taker_note = models.TextField( null = True )
    taker_obj_rating = models.IntegerField( default = 1 )
    taker_deal_rating = models.IntegerField( default = 1 )
    taker_conf = models.BooleanField( default = False )
    taker_conf_date = models.DateTimeField( null = True )
    created = models.DateTimeField( auto_now = False, auto_now_add = True )
    
    class Meta:
        db_table = 'items_delivery'

    def __unicode__(self):              # __unicode__ on Python 2
        return self.id
        
class RequestAlert(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, db_column='taker_id', null = True )
    item_reservation = models.ForeignKey(ItemReservation, db_column='reservation_id', related_name="request_alert", null = True )
    created = models.DateTimeField( auto_now = False, auto_now_add = True )
    
    class Meta:
        db_table = 'request_alerts'
        
class MyAdAlert(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, db_column='user_id', null = True )
    item = models.ForeignKey(Item, db_column='item_id', related_name="item_alert", null = True )
    created = models.DateTimeField( auto_now = False, auto_now_add = True )
    
    class Meta:
        db_table = 'my_ad_alerts'
        
class Report(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, db_column='user', null = True )
    item = models.ForeignKey(Item, db_column='item', related_name="item_report", null = True )
    reason = models.TextField( null = True )
    status = models.IntegerField( default = 1 )
    created = models.DateTimeField( auto_now = False, auto_now_add = True )
    
    class Meta:
        db_table = 'item_reports'

items/forms.py
import pudb
from django import forms    
from parent_categories.models import ParentCategorie

  
class add_item_form(forms.Form):
    parent_categories = []
    obj = ParentCategorie.objects.all()
    for x in obj:
        parent_categories.append((x.id,x.name))
    user_id = forms.IntegerField( widget = forms.HiddenInput( attrs = { 'class':'form-control' } ))
    parent_category_id = forms.IntegerField( required=False, label = 'Categorie Principale:', widget = forms.Select( attrs = { 'class':'form-control' }, choices = parent_categories ))
    child_category_id = forms.IntegerField( required=True, label = 'Categorie Secondaire:', widget = forms.Select( attrs = { 'class':'form-control' }, choices = [(1,'Veuillez selectionner une categorie principale.')] ))
    title = forms.CharField( required=False, label = 'Titre:', widget=forms.TextInput(attrs={'class':'form-control'}))
    credit = forms.CharField( required=False, label = 'Credit:', widget= forms.Select( attrs = { 'class':'form-control' }, choices = [(1, '1'), (2, '2'), (3, '3')] ))
    description = forms.CharField( required=False, label = 'Description:', widget=forms.Textarea(attrs={'class':'form-control'}))
    img1 = forms.FileField( required=False, label = 'Photo 1:', widget=forms.FileInput(attrs={'class':'form-control'}), initial = '')
    img2 = forms.FileField( required=False, label = 'Photo 2:', widget=forms.FileInput(attrs={'class':'form-control'}), initial = '')
    img3 = forms.FileField( required=False, label = 'Photo 3:', widget=forms.FileInput(attrs={'class':'form-control'}), initial = '')
    status_id = forms.IntegerField( widget = forms.HiddenInput( attrs = { 'class':'form-control' }), initial = 1)

  
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(add_item_form, self).__init__(*args, **kwargs)
        self.fields['user_id'].initial = self.user.id

items/templates/items/add_item copy.html
{% extends "base_generic.html" %}
    {% load staticfiles %}
    {% block Slider %}
    <!--=== Slider ===-->
    <!--=== End Slider ===-->
    {% endblock Slider %}
    {% block js %}
    <script type="text/javascript" src={% static "js/pages/item_add.js" %}></script>
    {% endblock js %}
    {% block content%}
            <div class="container">
            <div class="margin-bottom-10"></div>
               <div class="panel panel-green margin-bottom-10">
                    <div class="panel-heading">
                        <h3 class="panel-title"><i class="fa fa-tasks"></i> Ajouter un item.</h3>
                    </div>
                    <div class="panel-body">                                                      
                        <form class="margin-bottom-40" role="form" id="category_form" method="post" enctype="multipart/form-data" action="/items/add_item/">
                            {% csrf_token %}
                            {% for hidden in form.hidden_fields %}
                                {{ hidden }}
                            {% endfor %}
                            {% for field in form.visible_fields %}
                            {% if field.label == 'Categorie Principale:' or field.label == 'Categorie Secondaire:' %}
                                <div class="form-group col-md-6">
                                {% if form.errors.child_category_id %}<span class="color-red"> Ce champ est requis.</span>{% endif %}
                            {% elif field.label == 'Titre:' %}
                                <div class="form-group col-md-6">
                            {% elif field.label == 'Credit:' %}
                                <div class="form-group col-md-6">
                            {% elif field.label == 'Photo 1:' or field.label == 'Photo 2:' or field.label == 'Photo 3:'%}
                                <div class="form-group col-md-4">
                            {% else %}
                                <div class="form-group col-md-12">
                            {% endif %}
                                <label>{{ field.label }}</label>
                                {{ field }}
                            </div>                          
                            {% endfor %}
                            <div class="form-group col-md-1">                
                                <button type="submit" class="btn-u btn-u-green">Soumettre</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
    {% endblock content%}

{% block menu_active %}

    <script type="text/javascript">
        $("#topnav-sub-add-item").addClass("active");
        $("#topnav-items").addClass("active");
    </script>
{% endblock menu_active%}

items/templates/items/add_item.html
{% extends "base_generic.html" %}
{% load staticfiles %}
{% block Slider %}
<!--=== Slider ===-->
<!--=== End Slider ===-->
{% endblock Slider %}
{% block content%}
<div class="container">
    <div class="margin-bottom-10"></div>
    <div class="panel panel-green margin-bottom-10">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-tasks"></i> Ajouter un item.</h3>
        </div>
        <div class="panel-body">
            <form class="margin-bottom-40" role="form" id="category_form" method="post" enctype="multipart/form-data" action="/items/add_item/">
                {% csrf_token %}
                <input class="form-control" id="id_item_id" name="item_id" type="hidden" value="{{form.field.item_id}}" />
                <input class="form-control" id="id_user_id" name="user_id" type="hidden" value="{{profile.profile_data.id}}" />
                <input class="form-control" id="id_status_id" name="status_id" type="hidden" value="1" />
                <div class="form-group col-md-6">
                    <label>Catégorie Principale:</label><span class="color-red"> * </span>
                    <select class="form-control" id="id_parent_category_id" name="parent_category_id">
                    {% for option in form.field.parent_category_id.options %}
                    <option value="{{option.id}}" {% if form.field.parent_category_id.value == option.id %}selected="selected"{% endif %}>{{option.name}}</option>
                    {% endfor %}
                    </select>
                </div>
                <div class="form-group col-md-6">
                    <label>Catégorie Secondaire:</label><span class="color-red"> * </span>{{form.error.child_category_id | safe }}
                    <select class="form-control" id="id_child_category_id" name="child_category_id" data-id="{{form.field.child_category_id.value}}">
                    </select>
                </div>
                <div class="form-group col-md-6">
                    <label>Titre:</label><span class="color-red"> * </span>{{form.error.title | safe }}
                    <input class="form-control" id="id_title" name="title" type="text" value="{{form.field.title.value}}" maxlength="50"/>
                </div>
                <div class="form-group col-md-6">
                    <label>Crédit(s):</label><span class="color-red"> * </span>{{form.error.credit | safe }}
                    <select class="form-control" id="id_credit" name="credit">
                        <option value="">Veuillez sélectionner le nombre de crédits demandés.</option>
                        <option value="0" {% if form.field.credit.value == "0" %}selected="selected"{% endif %}>0</option>
                        <option value="1" {% if form.field.credit.value == "1" %}selected="selected"{% endif %}>1</option>
                        <option value="2" {% if form.field.credit.value == "2" %}selected="selected"{% endif %}>2</option>
                        <option value="3" {% if form.field.credit.value == "3" %}selected="selected"{% endif %}>3</option>
                    </select>
                </div>
                <div class="form-group col-md-12">
                    <label>Description:</label><span class="color-red"> * </span>{{form.error.description | safe }}
                    <textarea class="form-control" cols="40" id="id_description" name="description" rows="10">{% if form.field.description.value %}{{form.field.description.value}}{% endif %}</textarea>
                </div>
                {% if form.error %}
                <div class="row">
                    <div class="form-group col-md-4">
                        <span class="color-red">&nbsp;&nbsp;&nbsp;&nbsp;Veuillez resélectionner vos images </span>
                    </div>
                </div>
               {% endif %}
               <div class="row">
                    <div class="form-group col-md-4">
                        <label>Photo 1:</label> (Image principale){{form.error.image_1|safe}}
                        <input class="form-control" id="id_img1" name="img1" type="file"/>
                    </div>
                    <div class="form-group col-md-4">
                        <label>Photo 2:</label>{{form.error.image_2|safe}}
                        <input class="form-control" id="id_img2" name="img2" type="file"/>
                    </div>
                    <div class="form-group col-md-4">
                        <label>Photo 3:</label>{{form.error.image_3|safe}}
                        <input class="form-control" id="id_img3" name="img3" type="file"/>
                    </div>
               </div>
               <div class="row">
                    <div class="gallery-page">
                         <div class="form-group col-md-4 text-center">
                              {% if form.field.image_1.value %}
                                   <a class="thumbnail fancybox-button zoomer center-block" data-rel="fancybox-button" href="/{{ form.field.image_1.value.large.url}}">
                                        <span class="overlay-zoom">
                                        <img alt="" src="/{{ form.field.image_1.value.thumbnail.url}}" class="img-responsive center-block">
                                        <span class="zoom-icon"></span>
                                        </span>
                                   </a>
                                   <a href="/items/del_img/?item={{form.field.item_id}}&img=1" class="btn-u btn-u-xs rounded btn-u-red" type="button">Supprimer</a>
                              {% endif %}
                         </div>
     
                         <div class="form-group col-md-4 text-center">
                              {% if form.field.image_2.value %}
                                   <a class="thumbnail fancybox-button zoomer center-block" data-rel="fancybox-button" href="/{{ form.field.image_2.value.large.url}}">
                                   <span class="overlay-zoom">
                                        <img alt="" src="/{{ form.field.image_2.value.thumbnail.url}}" class="img-responsive center-block">
                                        <span class="zoom-icon"></span>
                                   </span>
                                   </a>
                                   <a href="/items/del_img/?item={{form.field.item_id}}&img=2" class="btn-u btn-u-xs rounded btn-u-red" type="button">Supprimer</a>
                              {% endif %}
                         </div>
                         
                         <div class="form-group col-md-4 text-center">
                              {% if form.field.image_3.value %}
                                   <a class="thumbnail fancybox-button zoomer center-block" data-rel="fancybox-button" href="/{{ form.field.image_3.value.large.url}}">
                                   <span class="overlay-zoom">
                                   <img alt="" src="/{{ form.field.image_3.value.thumbnail.url}}" class="img-responsive center-block">
                                   <span class="zoom-icon"></span>
                                   </span>
                                   </a>
                                   <a href="/items/del_img/?item={{form.field.item_id}}&img=3" class="btn-u btn-u-xs rounded btn-u-red" type="button">Supprimer</a>
                              {% endif %}
                         </div>
                    </div>
               </div>
               
               
                <div class="form-group col-md-4">                
                    <button type="submit" class="btn-u">Publier</button>
                    {% if form.field.item_id %}
                    <a href="/items/details/{{form.field.item_id}}/" class="btn-u btn-u-red">Annuler</a>
                    {% else %}
                    <a href="/items/" class="btn-u btn-u-red">Annuler</a>
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content%}
{% block js %}
    <script type="text/javascript" src={% static "js/pages/item_add.js" %}></script>
    <script type="text/javascript" src={% static "plugins/fancybox/source/jquery.fancybox.pack.js" %}></script>
{% endblock js %}
{% block jquery_init %}
    <script type="text/javascript">
        jQuery(document).ready(function() {
            App.init();
            App.initFancybox();
        });
    </script>
{% endblock jquery_init %}
{% block menu_active %}
    <script type="text/javascript">
        $("#topnav-sub-add-item").addClass("active");
        $("#topnav-items").addClass("active");
    </script>
{% endblock menu_active%}